### ISSUE TITLE
Add AADLoginForWindows extension

### ISSUE THREAD

**Issue by sandman-battelle** [battelle-cube/terraform-cube-avd#2]
>From: Johnson, Keith 
Sent: Wednesday, August 11, 2021 10:30 AM
To: Sandman, Mike 
Subject: AVD Extension
>
>Mike,
>
>Do you have the “AADLoginForWindows” Extension in the automation?   
>
>If not can we add it, this will enroll the machines in intune and allow them to be managed for antivirus if I’m not mistaken.
>
>https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows
>
>Keith Johnson
IT Infrastructure Administrator III
Corporate Information Technology
Office: 614.424.3836
>
>Battelle
505 King Avenue
Columbus, OH  43201
http://www.battelle.org

**Comment by valerio-battelle** [comment]
This does not seem possible in the Azure Gov Cloud.   According to this (https://docs.microsoft.com/en-us/azure/virtual-desktop/deploy-azure-ad-joined-vm) documentation

"Azure AD-joined VMs are currently only supported in the Azure Commercial cloud."

and this (https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows) documentation

"Remote connection to VMs joined to Azure AD is only allowed from Windows 10 PCs that are either Azure AD registered (starting Windows 10 20H1), Azure AD joined or hybrid Azure AD joined to the same directory as the VM."

I have setup a single VM AVD Workspace and have asked Terry and Keith to manually join to the domain and either confirm or deny this documentation.

**Comment by sandman-battelle** [comment]
Guessing this is done or dead based on activity. Please re-open if needed.
