### ISSUE TITLE
Fix issue where session host becomes unavailable

### ISSUE THREAD

**Issue by gaunt-battelle** [battelle-cube/terraform-cube-avd#41]
Unsure what causes this. Update issue with actual error and resolve.

Current workaround that needs an actual fix:
(appox 20 minutes)
1. Delete from host pool
2. Delete vm
3. Kick off terraform again

**Comment by sandman-battelle** [comment]
still needed? @gaunt-battelle

**Comment by gaunt-battelle** [comment]
Various things could have been causing it but I think we worked around or through it when moving to the terraform implementation.
