### ISSUE TITLE
Cannot modify extensions in the VM when the VM is not running

### ISSUE THREAD

**Issue by gaunt-battelle** [battelle-cube/terraform-cube-avd#43]
Find solution for below error. Note what causes it, possible workaround, etc.

[Failed run](https://tfe-prd.battelle.io/app/battelle/workspaces/avd-rob-dev/runs/run-ZrmwpeAV4fgQoLjQ)

Error: waiting for creation of Subscription Template Deployment "avdRobDev": Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"OperationNotAllowed\\\",\\r\\n    \\\"message\\\": \\\"Cannot modify extensions in the VM when the VM is not running.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]
│ 
│   with module.avd.azurerm_subscription_template_deployment.avd,
│   on .terraform/modules/avd/main.tf line 231, in resource "azurerm_subscription_template_deployment" "avd":
│  231: resource "azurerm_subscription_template_deployment" "avd" {

**Comment by sandman-battelle** [comment]
dead repo.  transfer to VDI?  or just close? @gaunt-battelle

**Comment by gaunt-battelle** [comment]
No need, this is a limitation of VM extensions. If we really want to send commands/scripts ad-hoc we'd need to wire up something like a GitHub action to power them on before their extensions can be modified.
