### ISSUE TITLE
enable ADE by default

### ISSUE THREAD

**Issue by sandman-battelle** [battelle-cube/terraform-cube-avd#54]
Set this variable to true to enable ADE. This will build a Key Vault and store the key for it with rotation.

variable "disk_encryption" {
  type = bool
  default = true
  description = "Enable BitLocker encrytion on the AVD session hosts and management VM, if applicable."
}

**Comment by rravenscroft** [comment]
@sandman-battelle  We can close this issue as we are doing this with our own ADE / CMK since the key Vault needs a random name to avoid purge protection from breaking destroys.  The enable = True builds a KV with a static name baked in from Jason Matson's script.

**Comment by rravenscroft** [comment]
We can close this as we are going to use Disk Encryption Sets.  Faster to deploy and a better overall solution for scaling builds.  We won't need ADE.
