### ISSUE TITLE
Make this repository private

### ISSUE THREAD

**Issue by gaunt-battelle** [battelle-cube/terraform-cube-avd#57]
The VMs need to reach out and grab scripts from github. Can we put these scripts in a storage account? Keep a separate public repo with only these? Other ideas?

**Comment by valerio-battelle** [comment]
ARM template implementation requires this repository to be public. To make this repo private we are going to implement the AVD ARM template functionality in terraform.

**Comment by gaunt-battelle** [comment]
Features needed for MVP
- [ ] start vm on connect (role + assigment)
- [ ] all hp properties
- [ ] diagnostics
- [ ] perf counters
- [ ] application groups
- [ ] host pool types
- [ ] disk encryption (bitlocker)
- [ ] automation accounts (vm start/end time, etc.)

**Comment by valerio-battelle** [comment]
This repository will be replaced by [terraform-cube-vdi](https://github.com/battelle-cube/terraform-cube-vdi)
